# Generated by Django 5.0.2 on 2024-03-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_returnproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
